### ISSUE TITLE
axios limitation < 1.0.0

### ISSUE THREAD

**Issue by Johann-S** [paraswap/paraswap-sdk#140] opened 2022-11-23 14:55 UTC
Hi,

first of all thanks for your awesome work 👍 

I want to use use `paraswap-sdk` in my project, but my `axios` lib version is up to date (currently: `v1.2.0`) and because of that I can't install your SDK. I think it would be bad to downgrade my version of Axios because of Paraswap SDK 😟 

![image](https://user-images.githubusercontent.com/1689750/203577570-303eb59f-e507-48de-b802-7b8740aadb41.png)

**Comment by Velenir** [comment] 2022-11-25 11:24
Thank you for bringing this to our attention.
This should be fixed in the [new release](https://github.com/paraswap/paraswap-sdk/releases/tag/v6.1.0), but you may want to downgrade your `axios` dependency to `v1.1.3` because of a [regression](https://github.com/axios/axios/issues/5298)..

Alternatively you could apply the following workaround:
```ts
import _axios from 'axios';
const axiosInst = _axios.create({
  headers: { 'Accept-Encoding': 'identity' },
});

const axios = {
  request: axiosInst.request.bind(axiosInst),
  isAxiosError: _axios.isAxiosError,
};
// use this `axios` when constructing SDK
```
But this way you would be opting out of response compression.

**Closed by Velenir** 2022-11-25 11:24 UTC

**Comment by Johann-S** [comment] 2022-11-25 12:47
Thanks for your workaround and quick answer! 👍
